# Generated by Django 3.0.6 on 2020-05-27 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_avatar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Avatar',
        ),
    ]
